language: cpp

compiler: g++

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq build-essential cmake

script:
    - cd src/main_compare; make
    - cd src/main_compare/test; ./init_test.sh make

dist: xenial
