dist: xenial

language: cpp

compiler: g++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - cmake

before_install:
  - export CXX=g++-4.8
  - export CC=gcc-4.8

script: scripts/build_ci.sh
