language: cpp

compiler: g++

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq build-essential cmake

script:
    - make build
    - make build_unit_test

after_success:
    - make unit_test

after_script:
    - make release

dist: xenial
